server:
  port: 9012
  servlet:
    session:
      timeout: 3600
    encoding: # 解决http请求编码问题
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
    accept-count: 100
    max-connections: 200
    threads:
      max: 100
      minSpare: 10
    connectionTimeout: 5000
  compression:
    enabled: true
  # 开启优雅停机kill -2 可以优雅停机
  shutdown: graceful
spring :
  profiles:
    active: dev
  application:
    name: demo-service
yxkong:
  tracing:
    enabled: true